clear;
clc;
f_antenna = 2*pi*2.4e9;
c = 3e8;
z0 = 1/200 * (c/(f_antenna/2/pi));
I0 = 1;
miu = 0.9999 *4 * pi *1e-7;
phi = linspace(0,2*pi,500);
theta = linspace(0,pi,500);
[tt,pp] = meshgrid(phi,theta);
U = (I0^2) *(z0^2)*(f_antenna^2 *miu)*(1/c)*(1/(32*pi))*((sin(pp).^2));
[x,y,z] = sph2cart(tt,pi/2-pp,U);
figure(1);
mesh(x,y,z);
title('The Radiation Pattern of Hertzian Dipole antenna in 3D by using sph2cart');
xlabel('phi'),ylabel('theta'),zlabel('U(\theta,\phi)');
figure(2);
mesh(phi,pi/2-theta,U);
title('The Radiation Pattern of Hertzian Dipole antenna in 3D');
xlabel('phi'),ylabel('theta'),zlabel('U(\theta,\phi)');
phi = linspace(eps , 2*pi , 100);
theta = linspace(pi/2, pi/2 , 100);
F_azmuth = (I0^2) *(z0^2)*(f_antenna^2 *miu)*(1/c)*(1/(32*pi))*(sin(theta).^2);
figure(3);
polar(phi,F_azmuth);
title('In azmuth plane');
theta = linspace (-pi,pi,100);
F_elevation = (I0^2) *(z0^2)*(f_antenna^2 *miu)*(1/c)*(1/(32*pi))*((sin(theta).^2));
figure(4);
polar(theta,F_elevation);
title('In elevation plane');

