% Create a horn antenna
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 21-Apr-2022 21:31:41

%% Antenna Properties 

antennaObject = design(horn, 11*1e9);
antennaObject.FlareLength = 0.27286;
antennaObject.FlareWidth = 0.16205;
antennaObject.FlareHeight = 0.12731;
antennaObject.Length = 0.039814;
antennaObject.Width = 0.02286;
antennaObject.Height = 0.01016;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 11000*1e6;
% Define frequency range 
freqRange = (9900:110:12100)*1e6;
% pattern
figure;
pattern(antennaObject, plotFrequency)

