% Create a dipole antenna
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 12-Mar-2022 00:56:42

%% Antenna Properties 

antennaObject = design(dipole, 2400*1e6);
antennaObject.Length = 0.062;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2400*1e6;
% Define frequency range 
freqRange = (2160:24:2640)*1e6;
% sparameter
figure;
s = sparameters(antennaObject, freqRange); 
rfplot(s)
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

