% Create a monopole antenna
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 12-Mar-2022 01:15:12

%% Antenna Properties 

antennaObject = design(monopole, 2400*1e6);
antennaObject.Height = 0.0307;
antennaObject.GroundPlaneLength = inf;
antennaObject.GroundPlaneWidth = inf;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2400*1e6;
% Define frequency range 
freqRange = (2160:24:2640)*1e6;
% pattern
figure;
pattern(antennaObject, plotFrequency)
% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)
% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

