% Create a yagiUda antenna
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 01-Apr-2022 23:01:52

%% Antenna Properties 

antennaObject = design(yagiUda, 260*1e6);
antennaObject.NumDirectors = 4;
antennaObject.DirectorLength = [0.4938,0.4846,0.4846,0.4938];
antennaObject.DirectorSpacing = 0.2885;
antennaObject.ReflectorLength = 0.5562;
antennaObject.ReflectorSpacing = 0.2308;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 260*1e6;
% Define frequency range 
freqRange = (234:2.6:286)*1e6;
% pattern
figure;
pattern(antennaObject, plotFrequency)

