% Create a linearArray with dipole element.
% Generated by MATLAB(R) 9.10 and Antenna Toolbox 5.0.
% Generated on: 02-May-2022 12:56:54

%% Array Properties 

SubObject = design(dipole, 2400*1e6);
arrayObject = design(linearArray('Element', SubObject), 2400*1e6, SubObject);
arrayObject.NumElements = 10;
arrayObject.ElementSpacing = 0.0625;

%% Array Analysis 
% Show for linearArray
figure;
show(arrayObject) 
% Layout for linearArray
figure;
layout(arrayObject) 
% Pattern for linearArray
PlotFrequency = 2400*1e6; Termination = 50;
figure;
pattern(arrayObject, PlotFrequency, 'Termination', Termination); 
% Azimuth for linearArray
PlotFrequency = 2400*1e6; azRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, PlotFrequency, azRange, 0, 'Termination', Termination);
% Elevation for linearArray
PlotFrequency = 2400*1e6; elRange = 0:5:360; Termination = 50;
figure;
pattern(arrayObject, PlotFrequency, 0, elRange, 'Termination', Termination);

